on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        ffmpeg-ver: [
          "4.4",
          "4.3",
          "4.2",
          "4.1"
        ]
        gcc-ver: [
          "11",
          "10",
          "9"
        ]
        arch: [
          "x86-64",
          "haswell",
        ]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-ver }}
    env:
      CFLAGS: -O3 -march=${{ matrix.arch }}
      CXXFLAGS: -O3 -march=${{ matrix.arch }}
    steps:
      - name: Install dependencies
        run: |
          apt update -qq
          apt -y install \
            autoconf \
            automake \
            build-essential \
            cmake \
            git-core \
            libass-dev \
            libfreetype6-dev \
            libgnutls28-dev \
            libsdl2-dev \
            libsoxr-dev \
            libtheora-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            meson \
            nasm \
            ninja-build \
            pkg-config \
            texinfo \
            yasm \
            zlib1g-dev
      - name: Clone FFMPEG ${{ matrix.ffmpeg-ver }}
        uses: actions/checkout@v2
        with:
          repository: FFmpeg/FFmpeg
          ref: release/${{ matrix.ffmpeg-ver }}
      - name: Clone FDK AAC
        uses: actions/checkout@v2
        with:
          repository: mstorsjo/fdk-aac
          path: ./fdk-aac
      - name: Compile FDK AAC
        run: |
          cd fdk-aac
          autoreconf -fiv
          ./configure --prefix="${GITHUB_WORKSPACE}/ffmpeg_build" \
            --disable-shared --enable-static
          make -j$(nproc)
          make install
          make distclean
      - name: Get LAME
        run: |
          wget http://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
          tar xzvf lame-3.100.tar.gz
          rm lame-3.100.tar.gz
      - name: Compile LAME
        run: |
          cd lame-3.100
          ./configure --prefix="${GITHUB_WORKSPACE}/ffmpeg_build" \
            --enable-nasm --disable-shared --enable-static
          make -j$(nproc)
          make install
          make distclean
      - name: Compile FFMPEG
        run: |
          ls -la
          find .
          export PKG_CONFIG_PATH="${GITHUB_WORKSPACE}/ffmpeg_build/lib/pkgconfig"
          ./configure --prefix="${GITHUB_WORKSPACE}/ffmpeg_build" \
            --extra-cflags="${CFLAGS} -I${GITHUB_WORKSPACE}/ffmpeg_build/include" \
            --extra-ldflags="-L${GITHUB_WORKSPACE}/ffmpeg_build/lib" \
            --bindir="${GITHUB_WORKSPACE}/bin" --extra-libs="-ldl" \
            --disable-shared \
            --enable-static \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-doc \
            --enable-libfdk-aac \
            --enable-libmp3lame \
            --enable-libsoxr \
            --enable-libtheora \
            --enable-libvorbis \
            --disable-encoders \
            --enable-encoder=aac \
            --enable-encoder=aac_at \
            --enable-encoder=aac_mf \
            --enable-encoder=flac \
            --enable-encoder=jpeg2000 \
            --enable-encoder=libfdk_aac \
            --enable-encoder=libmp3lame \
            --enable-encoder=libopus \
            --enable-encoder=libtheora \
            --enable-encoder=libvorbis \
            --enable-encoder=vorbis \
            --enable-encoder=zlib \
            --disable-decoders \
            --enable-decoder=aac \
            --enable-decoder=aac_at \
            --enable-decoder=aac_fixed \
            --enable-decoder=aac_latm \
            --enable-decoder=flac \
            --enable-decoder=jpeg2000 \
            --enable-decoder=libfdk_aac \
            --enable-decoder=libmp3lame \
            --enable-decoder=libopus \
            --enable-decoder=libtheora \
            --enable-decoder=libvorbis \
            --enable-decoder=pcm_s16le \
            --enable-decoder=pcm_s16le_planar \
            --enable-decoder=pcm_s24le \
            --enable-decoder=pcm_s24le_planar \
            --enable-decoder=vorbis \
            --enable-decoder=zlib
          make -j$(nproc)
          make install
      - name: Check binaries
        run: find . | grep ffprobe
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg${{ matrix.ffmpeg-ver }}-${{ matrix.arch }}-gcc${{ matrix.gcc-ver }}
          path: |
            ffmpeg
            ffplay
            ffprobe
